### PR TITLE
added singularity image recipe

### PR DESCRIPTION
**Pull request by mcduta**
initial recipe for a singularity image

### CODE REVIEW

**Comment by tschoonj** [comment]
Looking good to me!

Many thanks!

**Comment by tschoonj** [comment]
@dkazanc You may want to have a look at those tests failing on Travis-CI...

**Comment by nicwade** [comment]
Hi Mihai,  We've added some additional required checks that must pass before we merge pull requests.  Due to one of these requirements being added after you submitted your pull request, please could you rebase with master and then raise the pull request again.  Thanks!

**Comment by nicwade** [comment]
Tom has just informed me I didn't need to close this pull request and you can just rebase - apologies :-)

**Comment by tschoonj** [comment]
Hi @mcduta 

Basically you need to (assuming you are on this branch locally):

```
git fetch
git rebase origin/master
git push -f
```

**Comment by mcduta** [comment]
Hi all, sorry for the long delay, I've just done this.  The solution is out-of-date though, after Tom's changes, not sure it's useful.  Originally, it was a way to pass the Singularity recipe to Tom, you can feel free to discard it now and replace it with Tom's three recipes.

Cheers,

Mihai

________________________________

**Comment by nicwade** [comment]
Thanks Mihai.  In that case I will leave it up to @tschoonj

**Comment by tschoonj** [comment]
Many thanks Mihai for your work!

**Pull request closed without merging**
