### PR TITLE
Nics working branch

### PR DESCRIPTION
**Pull request by nicwade**

### CODE REVIEW

**Comment by tschoonj** [comment]
More background about the PyMca issue (and possibly a fix) can be found in #563

**Comment by nicwade** [comment]
Thanks!  I will have a look when I'm back in but I just need to get this commit into the master branch asap!

**Comment by tschoonj** [comment]
Sure thing, but before it can be merged in, a merge issue with environment.yml needs to be resolved...

**Comment by nicwade** [comment]
Done thanks!

**Pull request merged**
