### PR TITLE
Savu python37 move

### PR DESCRIPTION
**Pull request by dkazanc**
merging @dtasev Python 3 changes in #654 with the master

### CODE REVIEW

**Comment by dkazanc** [comment]
OK, this looks good now. The corresponding Jenkins server running Travis tests with Savu 3.0 from the branch: 
https://jenkins.diamond.ac.uk/view/SAVU/job/Savu3_0_py37_branch_travis/

**Comment by dkazanc** [comment]
I've added conda recipes for  **morphsnakes** and **geodesic distance**, however installation of compiled packages happens from my anaconda [channel](https://anaconda.org/dkazanc/dashboard). This should be maintainable. 
Additionally I added tests for **GeoDistance** segmentation and the 3D test fails due to _VOLUME_3D_ issue. @nicwade would you be able to fix this please since many segmentation tests require this pattern? 
WIP on other tests and clean up redundant ones.

**Comment by nicwade** [comment]
Thanks Daniil!  VOLUME_3D is near the top of my list :-)

**Comment by dkazanc** [comment]
I think all segmentation tests now added, so when  _VOLUME_3D_ is enabled they should pass in theory. 
Two things in question: **flupy** and **ptypy** packages
 **flupy** seems to be a missing fluorescence related package which does not exist in the current list of packages. 
**ptypy** is  pretty big package for ptychography which I guess we'd like to avoid incorporating into Savu? Could be a license issue as well. 
@nicwade  so what do we do with the plugins related? cheers

**Pull request merged**
