### PR TITLE
Iterative plugins API

### PR DESCRIPTION
**Pull request by dkazanc**

### CODE REVIEW

**Review by yousefmoazzam — COMMENTED** [review]
Here are some things that we have agreed are needed before the merge into `master` (we can update the list as we go along if we think of other things as well):
- some tests that run process lists with iterative loops
- general additions and improvements to the `iterate` command
- some configurator tests for the `iterate` command?
- remove any unnecessary print statements that have been added during development
- check it works with MPI mode
- (don't forget to add info to the CHANGELOG...)

**Comment by yousefmoazzam** [comment]
Commit f567bed adds a few tests for running iterative loops which have very simple cases, let me know if there are other cases that would be worth testing. One that could be useful is having a process list that has two or more loops in it?

**Comment by dkazanc** [comment]
thanks for the tests @yousefmoazzam. Should be enough to test the main iterative functionality, I will also add the iterative alignment test when it's working.

**Comment by dkazanc** [comment]
I've done some modifications in the iterate outlook, see the image. How does it look? @jessicavers the problem is that I cannot save the p_dict[iterative] into the nxs file apparently, so when I load it, all modifications lost. 
image

**Review by yousefmoazzam — APPROVED** [review]
We've covered most of the checklist from a previous comment on what should be done before the pull request is accepted/merged. It's only the MPI local testing leftover, which will be tackled at a later date in a more general context.

**Pull request merged**
