### PR TITLE
Update a default parameter of autocentering

### PR DESCRIPTION
**Pull request by nghia-vo**
This parameter helps to improve SNR it should be used as default.

### CODE REVIEW

**Comment by nghia-vo** [comment]
@nicwade : Don't know why the tests fail. I've just changed a parameter.

**Comment by nicwade** [comment]
The tests started failing last week. It fails when using tomopy but the version of tomopy doesn't seem to have changed so perhaps it's a library that it is dependent on. If you need something to go into pre-release via master branch quickly Tom would be a good person for help. Otherwise I can take a look next week.

Cheers,

Nicola.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tschoonj** [comment]
Looks indeed like a broken dependency:

```
E           OSError: /home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/tomopy/sharedlibs/libtomopy.so: undefined symbol: _ZN2cv19getRotationMatrix2DENS_6Point_IfEEdd
3272
3273
```

will investigate

**Comment by tschoonj** [comment]
As the error message already indicates: the problem lies with OpenCV which was updated from 4.1.1 to 4.1.2.

Until Savu fully supports python 3 I would recommend pinning opencv in `environment.yml` to 4.1.1.

**Pull request merged**
