### PR TITLE
Option to use min, mean, max datasets and speed updates

### PR DESCRIPTION
**Pull request by MattTaylorDLS**
Changes to kinematic stage motion plugin to give the option of using the combination of min, mean and max, based on values in the config file and/or in the data file meta data.

### CODE REVIEW

**Comment by DLSTasktop** [comment]
(Comment from Matthew Taylor):

Hi Nic,

 

Please could you run this against /dls/tmp/savu/big*test*mil*4mm.nxs using the config file in Savu/test*data/test*process*lists/kinematic*parser*test.nxs.

 

Will be interesting to see what time you get.

 

Thanks,

 

Matt

**Comment by DLSTasktop** [comment]
(Comment from Nicola Wadeson):

The data is not there anymore.  Can I find it anywhere else?

**Comment by DLSTasktop** [comment]
(Comment from Matthew Taylor):

I've just put it back in, hopefully it'll stay there long enough for you to run it / copy it out.

**Comment by DLSTasktop** [comment]
(Comment from Matthew Taylor):

I've just put it back in, hopefully it'll stay there long enough for you to run it / copy it out.

If you copy out, you'll also need the 4 PANDABOX files (001PANDABOX1mil.h5, 002PANDABOX1mil.h5, 007PANDABOX1mil.h5, 008PANDABOX1mil.h5)

**Comment by nicwade** [comment]
I've copied the data to my machine where local savu is installed in scratch, but IT still haven't switched my machine so I will have to wait until Daniil is not using it!


Cheers,


Nic.

________________________________

**Comment by DLSTasktop** [comment]
(Comment from Matthew Taylor):

OK cool, no rush!

**Comment by DLSTasktop** [comment]
(Comment from Nicola Wadeson):

I updated to current master Savu version in my scratch space and ran the test you suggested on one core, which took an average of 17.7 seconds.  I wasn't able to run savu*mpi*local version yet due to an error in my recent updates.  I did this in normal hdf5 transport mode, not basic mode.  Which mode were you using and what times were you seeing?

Cheers,

Nic.

**Comment by DLSTasktop** [comment]
(Comment from Matthew Taylor):

Ah, that's pretty good.

I'm just running normal savu mode, not basic mode (I can't remember the command to run that). It takes an average of about 70 seconds for me. Of that, about 40-45 is "setup" time and 20 seconds is when it's actually running through the plugin.

Thanks for testing that, it's good to know.

**Comment by MattTaylorDLS** [comment]
Further test. Sorry Nic

**Comment by DLSTasktop** [comment]
(Comment from Matthew Taylor):

Jira test

**Pull request merged**
