### PR TITLE
Don't fail GPU check when not using GPU processes

### PR DESCRIPTION
**Pull request by hir12111**
This change makes GPU dependencies optional if you are not using GPU
plugins

### CODE REVIEW

**Comment by DLSTasktop** [comment]
(Comment from Nicola Wadeson):

Hi Emilio,

Can you report what error you were getting first?  Thanks!

**Comment by DLSTasktop** [comment]
(Comment from Emilio PJ):

it was an ImportError because I don't have dependency pynvml (and I don't need it)

 

Regards

**Comment by DLSTasktop** [comment]
(Comment from Emilio PJ):

Example:

> savu --transport dosna --dosna*engine=cpu --dosna*backend=ram 24737.nxs commands .

USER:root:User Log Started  

USER:root:User Log location is './20180810120941_24737/user.log'  

Traceback (most recent call last):  

 File "/home/hir12111/venv27/bin/savu", line 11, in <module>  

 load*entry*point('savu', 'console_scripts', 'savu')()  

 File "/scratch/emilio/src/Savu/savu/tomo_recon.py", line 216, in main  

 plugin*runner.*run*plugin*list()  

 File "/scratch/emilio/src/Savu/savu/core/plugin*runner.py", line 52, in*run*plugin*list  

 self.*run*plugin*list*check(plugin_list)  

 File "/scratch/emilio/src/Savu/savu/core/plugin*runner.py", line 132, in*run*plugin*list_check  

 self.*_check*gpu()  

 File "/scratch/emilio/src/Savu/savu/core/plugin*runner.py", line 178, in**check*gpu  

 if not self.exp.meta*data.plugin*list.*contains*gpu_processes():  

 File "/scratch/emilio/src/Savu/savu/data/plugin*list.py", line 341, in*contains*gpu*processes  

 from savu.plugins.driver.gpu_plugin import GpuPlugin  

 File "/scratch/emilio/src/Savu/savu/plugins/driver/gpu_plugin.py", line 28, in <module>  

 import pynvml as pv  

ImportError: No module named pynvml

**Comment by DLSTasktop** [comment]
(Comment from Emilio PJ):

I'm not sure why the test to [https://github.com/DiamondLightSource/Savu/pull/517](https://github.com/DiamondLightSource/Savu/pull/517) are not passing and I saw it happens since commit 6bd4bf8f516175a5e8500783f20f80b9387e1daf, are the travis tests broken?

**Comment by DLSTasktop** [comment]
(Comment from Emilio PJ):

I'm not sure why the test to [https://github.com/DiamondLightSource/Savu/pull/517](https://github.com/DiamondLightSource/Savu/pull/517) are not passing and I saw it happens since commit 6bd4bf8f516175a5e8500783f20f80b9387e1daf, are the travis test scripts broken?

**Comment by nicwade** [comment]
The nvidia-ml-py package, which contains pynvml, comes packaged with Savu.  Which version of Savu are you using (i.e. the module load version and subsequent conda environment, not your local Savu repo)?
And yes, I am currently fixing the broken tests :-).

**Comment by DLSTasktop** [comment]
(Comment from Nicola Wadeson):

Ah ok, it makes sense now then :).  Would you mind updating the pull request so it still throws an exception on anything else other than the failed import of pynvml?  I don't really want any other issues to be hidden by the try-except statement.

**Comment by hir12111** [comment]
It works like that already, the except block is only affecting ImportError's so the other exceptions will be raised, furthermore, the logging message is showing what dependency would be having the import error

**Comment by DLSTasktop** [comment]
(Comment from Nicola Wadeson):

Yes, but it doesn't fail on import errors other than pynvml

**Comment by hir12111** [comment]
keep in mind that this is only affecting the part checking if there are gpu plugins, if there are import errors and you are using GPU plugins then the proper ImportError will be raised later,
do you want me to check if the exception message contains pynvml and if not reraise the ImportError?

**Comment by DLSTasktop** [comment]
(Comment from Nicola Wadeson):

Yes please

**Comment by hir12111** [comment]
Done

**Pull request merged**
